name: API Tests

on: 
  pull_request:
    branches:
      [main,dev]

jobs: 
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version}}
      - name: npm install
        run: npm ci
      - name: fire up backend 
        run: nohup npm run backend & exit
      # - name: newman test
      #   run: npm test
      - name: gui testing
        run: npm test