name: API deploy

on:
  pull_request:
    types: [closed]
    branches: [main]


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: wait for the merge to get to the server 
      # using ssh-action from appleboy
        uses: jakejarvis/wait-action@master
        with:
          time: '60s'
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          # using repository secrets
          # for login to your server
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          # commands to run on your server
          # below just an example
          # can be more (like restarting pm2)
          script: |
            echo "cd to correct folder"
            cd /var/demo-deploy-action
            echo "git pull"
            git pull
            echo "npm install"
            npm install
            echo "running build if present"
            npm run build --if-present
            echo "restarting app in pm2"
            pm2 restart lumia